spring:
  application:
    name: api-gateway
  
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8088}
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/user/**
        - id: product-service
          uri: http://product-service:8081
          predicates:
            - Path=/products/**
        - id: cart-service
          uri: http://cart-service:8082
          predicates:
            - Path=/userCart/**
        - id: wishlist-service
          uri: http://wishlist-service:8083
          predicates:
            - Path=/userWishList/**

app:
  eureka-server: localhost