spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/userCart/**
        - id: wishlist-service
          uri: lb://wishlist-service
          predicates:
            - Path=/userWishList/**
        - id: fabon-reader
          uri: lb://fabon-reader
          predicates:
            - Path=/fabonUser/**

